# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker release image

on:
  push:
    branches:
      - 'release/v*'
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Extract Version
        id: get_version
        uses: battila7/get-version-action@v2.2.1

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract nacos-server metadata (tags, labels) for Docker
        id: nacos-server-meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/nacos-server
          tags: |
            type=raw,value=${{ steps.get_version.outputs.version }}
            type=semver,pattern={{raw}}

      - name: build nacos
        uses: docker/build-push-action@v2.3.0
        with:
          context: ./build
          file: ./build/Dockerfile
          push: true
          tags: ${{ steps.nacos-server-meta.outputs.tags }}
          labels: ${{ steps.nacos-server-meta.outputs.labels }}
          target: nacos-release
          platforms: linux/amd64,linux/arm64
          build-args: "NACOS_VERSION=${{ steps.get_version.outputs.version-without-v }}"
      
      - name: Extract mysql-57 metadata (tags, labels) for Docker
        id: mysql-57-meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/mysql-57
          tags: |
            type=raw,value=${{ steps.get_version.outputs.version }}
            type=semver,pattern={{raw}}
      
      - name: build mysql 5.7
        uses: docker/build-push-action@v2.3.0
        with:
          context: ./build
          file: ./build/Dockerfile
          push: true
          tags: ${{ steps.mysql-57-meta.outputs.tags }}
          labels: ${{ steps.mysql-57-meta.outputs.labels }}
          platforms: linux/amd64
          target: mysql5.7
      
      - name: Extract mysql-8 metadata (tags, labels) for Docker
        id: mysql-8-meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/mysql-8
          tags: |
            type=raw,value=${{ steps.get_version.outputs.version }}
            type=semver,pattern={{raw}}   
      
      - name: build mysql 8
        uses: docker/build-push-action@v2.3.0
        with:
          context: ./build
          file: ./build/Dockerfile
          push: true
          tags: ${{ steps.mysql-8-meta.outputs.tags }}
          labels: ${{ steps.mysql-8-meta.outputs.labels }}
          target: mysql8
          platforms: linux/amd64